### PR TITLE
Dockless view refactor

### LINKED ISSUE #113: Scooter - Stat DAG Fail -  No Space Left on Device
@RMK0110 can you tag a look at some of the DAG run logs? [this](https://stackoverflow.com/questions/29602409/could-not-write-to-hash-join-temporary-file-no-space-left-on-device) might be a lead

### LINKED ISSUE #135: Improve reliability of MDS materialized view refreshes
Refreshing the materialized views of mds data has been failing the last few months due to running out of local disk space (cf. #113). It seems that this job is a bit large for the current RDS size. We have discussed a few was to fix this:

### Increase instance size
**Pros:**
* Probably easier
* May have other positive effects in query times

**Cons:**
* Costs more
* Doesn't really address the underlying issue, could rear its head again

### Use view instead of materialized view
**Pros:**
* Much less computationally expensive to create.
* Better freshness features than materialized views.

**Cons:**
* May have less performant analysis queries
* Can't set an index on a view (AFAIK)

### Roll our own materialized view table
**Pros:**
* Allows incremental updates
* Keeps indices working

**Cons:**
* Easy to get wrong.

### Somehow optimize the materialized view
**Pros:**
* Keeps the nice features of materialized views (indices, query times)

**Cons:**
* How do we do it?

### Make the materialized view cover a limited time
**Pros:**
* Easy, probably effective

**Cons:**
* Makes historical analysis more challenging

### PR DESCRIPTION
**Pull request by ian-r-rose**
Fixes #135, fixes #113, follow-up to #136.

I have set some indices on the underlying `trips`, `trips_geoms`, `status_changes`, and `status_changes_geoms` tables. Once these are set, I believe that a regular view is competitive with a materialized view. If we later find this not to be the case, we can restore the materialized view for the last 30-60 days to to keep it smaller and more focused.

This should be almost entirely a drop-in replacement for the materialized view, with one caveat: in the previous materialized view `start_time_local` and `end_time_local` were indexed columns, whereas here `start_time`, and `end_time` are indexed (that is, the UTC timestamps). This is because the local versions are derived quantities from the UTC versions, and are thus not sargable unless materialized. Code that was making use of those indexes would need to be updated with some extra time zone logic.

### CODE REVIEW

File: dags/transportation/dockless/indexes.sql [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+DROP INDEX IF EXISTS idx_trips_start_time;
+DROP INDEX IF EXISTS idx_trips_end_time;
+DROP INDEX IF EXISTS idx_trip_geom_points;
+DROP INDEX IF EXISTS idx_status_change_geoms_event_location_geom;
+
+
+ALTER TABLE public.trips_geoms
+    ADD CONSTRAINT pk_trip_geom_id PRIMARY KEY (trip_id);
+
+CREATE INDEX idx_status_changes_event_time
```
Comment (hunterowens) [inline dags/transportation/dockless/indexes.sql]: change to CREATE IF NOT EXISTS?

File: dags/transportation/dockless/scooter-stat.py [hunk 2]
```diff
@@ -159,6 +134,4 @@ def email_callback(**kwargs):
     dag=dag,
 )
 
-task1.set_downstream(set_xcom)
-task2.set_downstream(set_xcom)
 email_task.set_upstream(set_xcom)
```
Comment (hunterowens) [inline dags/transportation/dockless/scooter-stat.py]: rewrite as `set_xcom > email_task`? also perhaps rename as `computer_stats` and `send_email`?

File: dags/transportation/dockless/indexes.sql (hunk 1 above)
Comment (ian-r-rose) [reply dags/transportation/dockless/indexes.sql]: Rather than the dropping above? Sure.

File: dags/transportation/dockless/scooter-stat.py (hunk 2 above)
Comment (ian-r-rose) [reply dags/transportation/dockless/scooter-stat.py]: Yeah, that's clearer.

**Comment by hunterowens** [comment]
this looks good to me. 

one sort of methodological note, is we haven't been keeping track of migrations. the way `indexes.sql` is written, is it reads as sort of a migration script. In that case, we should probably keep the "original" schemas and then follow on migration scripts in a folder as such. 

```

migrations/
├── 001-m_view.sql
├── 002-indexes.sql
└── init.sql
```

**Comment by ian-r-rose** [comment]
Interesting. How would you envision that would work along with the table creation logic in various DAGs? That is to say, a number of the DAGs (including dockless) have code to create the table. Do you think we would want to refactor those to successively apply migrations?

**Comment by hunterowens** [comment]
upon second reading, I think it is actually fine, as the ALTER_TABLES aren't about fields, just indexing

**Comment by ian-r-rose** [comment]
Yeah, none of the schemas actually change here, just some indices and one mview -> view
